# Generated by Django 2.2.5 on 2020-01-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkPermissionStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255, unique=True)),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group')),
            ],
        ),
    ]
