# Generated by Django 2.2.9 on 2020-03-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AugmentEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('capacity_added', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('user', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'augment_entries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AugmentEntryView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='DATE')),
                ('legacy_company', models.CharField(max_length=6)),
                ('a_location', models.CharField(blank=True, max_length=50, null=True)),
                ('z_location', models.CharField(blank=True, max_length=50, null=True)),
                ('a_node', models.CharField(max_length=50)),
                ('z_node', models.CharField(max_length=50)),
                ('segment_type', models.CharField(max_length=9)),
                ('capacity_added', models.IntegerField()),
                ('path_id', models.IntegerField()),
            ],
            options={
                'db_table': 'augment_entry_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_capacity_gbps', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('user', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'current_capacity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='DATE')),
                ('path_id', models.IntegerField(blank=True, null=True)),
                ('legacy_company', models.CharField(blank=True, max_length=6, null=True)),
                ('a_location', models.CharField(blank=True, max_length=50, null=True)),
                ('z_location', models.CharField(blank=True, max_length=50, null=True)),
                ('a_node', models.CharField(blank=True, max_length=50, null=True)),
                ('z_node', models.CharField(blank=True, max_length=50, null=True)),
                ('current_capacity_gbps', models.IntegerField(blank=True, null=True)),
                ('capacity_gbps', models.DecimalField(blank=True, decimal_places=0, max_digits=33, null=True)),
                ('ssp_traffic_gbps', models.FloatField()),
                ('wcf_traffic_gbps', models.FloatField()),
            ],
            options={
                'db_table': 'dashboard_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location', models.CharField(max_length=50, unique=True)),
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('user', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_name', models.CharField(max_length=50, unique=True)),
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('legacy_company', models.IntegerField()),
                ('segment', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('user', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'node',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('path_id', models.IntegerField(primary_key=True, serialize=False)),
                ('leased', models.CharField(max_length=5)),
                ('created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('user', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'path',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PathInfoView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_company', models.CharField(max_length=6)),
                ('a_location', models.CharField(blank=True, max_length=50, null=True)),
                ('z_location', models.CharField(blank=True, max_length=50, null=True)),
                ('a_node', models.CharField(max_length=50)),
                ('z_node', models.CharField(max_length=50)),
                ('segment_type', models.CharField(max_length=9)),
                ('path_id', models.IntegerField()),
            ],
            options={
                'db_table': 'path_info_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrafficInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ssp_traffic_gbps', models.FloatField()),
                ('path_id', models.IntegerField()),
                ('wcf_traffic_gbps', models.FloatField()),
                ('created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('user', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'traffic_info',
                'managed': False,
            },
        ),
    ]
